App:
  environment: "dev"
kafka:
  brokers: ["localhost:9092"]
  topic: "security-assessment"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "your_password"
  dbName: "your_database_name"
  sslMode: "disable"
  MaxOpenConnections: 100
  MaxIdleConnections: 10
  connMaxLifetime: 3600