App:
  environment: "dev"
kafka:
  brokers: ["localhost:9092"]
  topics: ["security-assessment"]
  groupID: "security-assessment-ingestion-group"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password:
  dbName:
  sslMode: "disable"
  MaxOpenConnections: 100
  MaxIdleConnections: 10
  connMaxLifetime: 3600